on: [push]

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-22.04
    container:
      image: wonderlandengine/editor:latest
    steps:
    - uses: actions/checkout@v2
    - name: package
      run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project MyWonderland.wlp --credentials "$WLE_CREDENTIALS"
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: Gzip
      run: gzip -k deploy/*
    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: wonderland-test
        path: deploy/
  deploy:
    needs: package
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: wonderland-test
        path: deploy
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: deploy
